from __future__ import annotations

import argparse
import json
import subprocess
import sys
from http import HTTPStatus
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "report"
SOURCES = ROOT / "sources"
BUILD_SCRIPT = ROOT / "code" / "build_report.py"


def resolve_markdown_source(source: str) -> Path:
    if not source or Path(source).is_absolute():
        raise ValueError("Invalid Markdown source path.")
    candidate = (SOURCES / source).resolve()
    sections_root = (SOURCES / "sections").resolve()
    if sections_root not in candidate.parents:
        raise ValueError("Markdown source must be inside sources/sections.")
    if candidate.suffix.lower() != ".md":
        raise ValueError("Markdown source must be a .md file.")
    return candidate


def build_script_can_regenerate() -> bool:
    if not BUILD_SCRIPT.exists():
        return False
    text = BUILD_SCRIPT.read_text(encoding="utf-8", errors="ignore")
    return "HTML report is generated by tools/" not in text and "def main" in text


def update_section_html(source: Path, markdown: str) -> None:
    source_name = source.name
    target = REPORT / "sections" / source.with_suffix(".html").name
    if not target.exists():
        return
    text = target.read_text(encoding="utf-8")
    if source_name not in text:
        return
    escaped = __import__("html").escape(markdown.rstrip())
    text = re_sub_textarea(text, escaped)
    target.write_text(text, encoding="utf-8")


def re_sub_textarea(text: str, escaped_markdown: str) -> str:
    import re

    pattern = r'(<textarea[^>]*class="[^"]*\b(?:md-editor|markdown-editor)\b[^"]*"[^>]*>)(.*?)(</textarea>)'
    return re.sub(pattern, lambda match: match.group(1) + escaped_markdown + match.group(3), text, count=1, flags=re.S)


class ReportHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(REPORT), **kwargs)

    def send_json(self, status: HTTPStatus, payload: dict[str, object]) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self) -> None:
        if self.path != "/api/save-section":
            self.send_error(HTTPStatus.NOT_FOUND, "Unknown API endpoint.")
            return

        try:
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length).decode("utf-8"))
            source = resolve_markdown_source(str(payload.get("source", "")))
            markdown = str(payload.get("markdown", "")).rstrip() + "\n"
            source.parent.mkdir(parents=True, exist_ok=True)
            source.write_text(markdown, encoding="utf-8")
            update_section_html(source, markdown)
            if build_script_can_regenerate():
                subprocess.run([sys.executable, str(BUILD_SCRIPT)], cwd=str(ROOT.parents[0]), check=True)
                update_section_html(source, markdown)
        except Exception as exc:
            self.send_json(HTTPStatus.BAD_REQUEST, {"ok": False, "error": str(exc)})
            return

        self.send_json(HTTPStatus.OK, {"ok": True, "source": str(source.relative_to(SOURCES))})


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the Uzbekistan report with persistent Markdown saving.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args()

    REPORT.mkdir(parents=True, exist_ok=True)
    server = ThreadingHTTPServer((args.host, args.port), ReportHandler)
    print(f"Serving {REPORT} at http://{args.host}:{args.port}/index.html")
    print("Use this URL for permanent Markdown editing through the Save button.")
    server.serve_forever()


if __name__ == "__main__":
    main()
